languageCode = "ja-JP"
title = "Yudai Tanaka"
baseurl = "http://ytnk531.github.io/"
theme = "aerial"

[params]
  name = "Yudai Tanaka"
  about = "ソフトウェアエンジニア &nbsp;&bull;&nbsp; 1992年生まれ &nbsp;&bull;&nbsp; メガネ"
  #copyright = "Untitled"
  #Disable the scrolling background by entering any string for bg_scroll. Enable by leaving bg_scroll empty.
  bg_scroll = "none"
  favicon = "favicon.ico"


[[params.social]]
  medium = "Github"
  icon = "github"
  link = "https://github.com/ytnk531"

[[params.social]]
  medium = "HatenaBlog"
  icon = "question"
  link = "http://ytnk531.hatenablog.com/"

[[params.social]]
  medium = "Qiita"
  icon = "quora"
  link = "https://qiita.com/ytnk531"

[[params.social]]
  medium = "Twitter"
  icon = "twitter"
  link = "https://twitter.com/__ytnk__"

[[params.social]]
  medium = "Facebook"
  icon = "facebook"
  link = "https://www.facebook.com/yudai.tanaka.773"

[[params.social]]
  medium = "Email"
  icon = "envelope-o"
  link = "ytnk531@gmail.com"

